from pathlib import Path
import json, base64, zipfile, io, os, tempfile
from playwright.sync_api import sync_playwright
from PIL import Image
OUT=Path(os.environ.get('STEM_BROWSER_ARTIFACTS', tempfile.mkdtemp(prefix='stem-browser-')))
OUT.mkdir(parents=True, exist_ok=True)
URL='http://127.0.0.1:'+os.environ.get('STEM_BROWSER_PORT','18768')
report={'fixture':'Two synthetic BF/HAADF pairs; actual host model.js, settings(), CSS, upload/change/fetch/infer lifecycle', 'checks':[]}
def check(name, value):
    assert value, name
    report['checks'].append(name)
with sync_playwright() as pw:
    browser=pw.chromium.launch(executable_path=os.environ.get('STEM_BROWSER_EXECUTABLE'),headless=True,args=['--no-sandbox','--disable-gpu'])
    page=browser.new_page(viewport={'width':1280,'height':960},accept_downloads=True)
    errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
    network=[];console=[]
    page.on('requestfailed',lambda r:network.append({'url':r.url,'failure':r.failure}))
    page.on('response',lambda r:network.append({'url':r.url,'status':r.status}) if r.status>=400 else None)
    page.on('console',lambda m:console.append(m.text) if m.type=='error' else None)
    page.goto(URL+'/')
    def ready(count=None):
        page.wait_for_function("document.querySelector('.stem-results')?.dataset.revision && ![...document.querySelectorAll('button')].find(b=>b.textContent==='Download images (.zip)')?.disabled && [...document.querySelectorAll('.stem-annotated')].every(i=>i.complete && i.naturalWidth)")
        if count is not None: page.wait_for_function('(n)=>document.querySelector(".stem-results").dataset.particleCount===String(n)',arg=count)
    def control(name, value):
        page.locator('[data-control='+name+']').evaluate('(e,v)=>{e.value=String(v);e.dispatchEvent(new Event("input"))}',value)
    def clicktext(text): page.get_by_role('button',name=text,exact=True).click()
    def pixels():
        return page.locator('.stem-annotated').evaluate_all('els=>els.map(i=>{let c=document.createElement("canvas");c.width=i.naturalWidth;c.height=i.naturalHeight;c.getContext("2d").drawImage(i,0,0);return c.toDataURL()})')
    ready(2)
    check('both modalities render both samples at natural size with proportional CSS scaling',page.locator('.stem-annotated').evaluate_all('els=>els.map(i=>[i.naturalWidth,i.naturalHeight,i.clientWidth,i.clientHeight])')==[[800,400,512,256],[800,400,512,256],[400,200,400,200],[400,200,400,200]])
    baseline=pixels()
    report['image_dimensions']=page.locator('.stem-annotated').evaluate_all('els=>els.map(i=>[i.naturalWidth,i.naturalHeight,i.clientWidth,i.clientHeight])')
    for index,image in enumerate(page.locator('.stem-annotated').all()):
        image.scroll_into_view_if_needed()
        screenshot=image.screenshot(path=str(OUT/f'visible-image-{index}.png'))
        visible=Image.open(io.BytesIO(screenshot)).convert('RGB')
        check(f'image {index}: actual viewport pixels show overlay colors',len(visible.getcolors(1000000))>3)
    page.locator('.stem-annotated').first.scroll_into_view_if_needed()
    check('no inline counts, captions, filenames, or status prose', page.locator('#results figcaption, #results [role=status]').count()==0)
    response=page.request.get(URL+'/response.json').json()
    expected=[{'name':n,'color':'rgb('+', '.join(map(str,c))+')'} for n,c in zip(response['segmentation'][0]['classes'],response['segmentation'][0]['colors'])]
    check('compact segmentation legend names and colors match response',page.locator('.stem-class-legend > span').evaluate_all('els=>els.map(e=>({name:e.textContent,color:e.firstElementChild.style.backgroundColor}))')==expected)
    page.screenshot(path=str(OUT/'combined.png'),full_page=True)
    page.get_by_role('button',name='STEM visualization settings').click()
    check('native host settings dialog opens',page.locator('dialog').evaluate('(d)=>d.open'))
    page.screenshot(path=str(OUT/'settings.png'),full_page=True)
    control('threshold',0);ready(4)
    check('lowering score threshold recovers all retained candidates',True)
    control('minRadius',25);ready(1)
    check('radius threshold uses original pixels',True)
    control('minRadius',0);ready(4)
    control('threshold',.95);ready(1)
    check('raising score threshold removes detections and accepts scores above one',True)
    page.locator('[data-class-name="Film"]').uncheck();ready(1)
    hidden=pixels()
    check('legend reflects selected classes after hiding Film',page.locator('.stem-class-legend > span').all_text_contents()==['Carbon','Vacuum'])
    check('hiding segmentation does not hide remaining particles',page.locator('.stem-results').get_attribute('data-particle-count')=='1')
    page.screenshot(path=str(OUT/'filtered-settings.png'),full_page=True)
    clicktext('Ok')
    with page.expect_download() as pending: clicktext('Download images (.zip)')
    pending.value.save_as(OUT/'filtered.zip')
    archive=zipfile.ZipFile(OUT/'filtered.zip');check('ZIP has four original-resolution modality plots',len(archive.namelist())==4)
    for i,name in enumerate(archive.namelist()):
        decoded=Image.open(io.BytesIO(archive.read(name))).convert('RGB')
        displayed=Image.open(io.BytesIO(base64.b64decode(hidden[i].split(',')[1]))).convert('RGB')
        check(f'{name}: ZIP pixels equal current display',decoded.tobytes()==displayed.tobytes())
        check(f'{name}: original dimensions',decoded.size==((800,400) if i<2 else (400,200)))
        w,h=decoded.size
        check(f'{name}: hidden Film pixels restore background',decoded.getpixel((w//2,30))==((40,)*3 if i%2==0 else (80,)*3))
        base=Image.open(io.BytesIO(base64.b64decode(baseline[i].split(',')[1]))).convert('RGB')
        check(f'{name}: other class pixels unchanged',decoded.getpixel((30,30))==base.getpixel((30,30)))
        point=(639,200) if i<2 else (319,100)
        old=base.getpixel(point);new=decoded.getpixel(point)
        check(f'{name}: original-pixel circle radius and threshold',old[1]>150 and (new[1]<150 if i<2 else new[1]>150))
    mask_href=page.locator('a[download="1-semantic-mask.png"]').get_attribute('href')
    mask=Image.open(io.BytesIO(base64.b64decode(mask_href.split(',')[1])))
    check('class-ID mask remains faithful with Film hidden',mask.getpixel((400,30))==1 and set(mask.get_flattened_data())=={0,1,2})
    page.get_by_role('button',name='STEM visualization settings').click();control('threshold',0);ready(4);clicktext('Cancel');ready(1)
    check('Cancel restores accepted view',True)
    page.get_by_role('button',name='STEM visualization settings').click();control('threshold',0);ready(4);page.keyboard.press('Escape');ready(1)
    check('Escape restores accepted view',True)
    page.reload();ready(1)
    check('accepted settings persist after reload',not page.locator('[data-class-name="Film"]').is_checked())
    page.get_by_role('button',name='STEM visualization settings').click();clicktext('None');ready(1)
    check('legend hidden when no segmentation classes selected',not page.locator('.stem-class-legend').is_visible())
    check('None clears all semantic visibility, independently of particles',all(not x for x in page.locator('[data-class-name]').evaluate_all('els=>els.map(e=>e.checked)')))
    clicktext('All');ready(1);check('All restores class visibility',all(page.locator('[data-class-name]').evaluate_all('els=>els.map(e=>e.checked)')));clicktext('Ok')
    for mode in ['particles','segmentation','empty']:
        page.evaluate('(mode)=>runFixture(mode)',mode);page.wait_for_timeout(300);ready()
        check(mode+': one settings control, no stale duplicates',page.locator('.settings').count()==1)
        check(mode+': images have nonzero visible layout',page.locator('.stem-annotated').evaluate_all('els=>els.every(i=>i.clientWidth>0 && i.clientHeight>0)'))
        check(mode+': legend only with segmentation',page.locator('.stem-class-legend').count()==(1 if mode=='segmentation' else 0))
        if mode=='particles':check('particle-only disables semantic controls',page.locator('dialog fieldset').evaluate('(e)=>e.disabled'))
        else:check(mode+': particle controls disabled',page.locator('[data-control=threshold]').is_disabled())
        if mode=='empty':check('empty output disables settings',page.locator('.settings').is_disabled())
    page.evaluate('document.querySelector("form").reset()');check('reset removes stale settings',page.locator('.settings').count()==0)
    page.evaluate("localStorage.setItem('toolbox-ui-stem-inference','broken');runFixture()")
    page.wait_for_timeout(300);ready(2);check('malformed saved settings safely fall back',True)
    if os.environ.get('STEM_REAL_PNG_DIR'):
        # Real PNG source pair with explicitly synthetic predictions; not a model-accuracy test.
        real=Path(os.environ['STEM_REAL_PNG_DIR'])
        files=[real/f'PtCo_IL_a-0016_{m}.png' for m in ['BF','HAADF']]
        page.locator('#infer input[type=file]').set_input_files(files)
        page.wait_for_function('document.querySelectorAll(".stem-annotated").length===2');ready(1)
        report['real_sample_dimensions']=page.locator('.stem-annotated').evaluate_all('els=>els.map(i=>[i.naturalWidth,i.naturalHeight,i.clientWidth,i.clientHeight])')
        check('real BF and HAADF PNGs decode at original dimensions', [x[:2] for x in report['real_sample_dimensions']]==[list(Image.open(f).size) for f in files])
        page.get_by_role('button',name='STEM visualization settings').click();clicktext('None');control('threshold',1);clicktext('Ok');ready(0)
        real_pixels=pixels()
        for index,image in enumerate(page.locator('.stem-annotated').all()):
            image.scroll_into_view_if_needed()
            image.screenshot(path=str(OUT/f'real-{index}-visible.png'))
            original=Image.open(files[index]).convert('RGB')
            rendered=Image.open(io.BytesIO(base64.b64decode(real_pixels[index].split(',')[1]))).convert('RGB')
            check(f'real modality {index}: hiding all overlays exactly restores source pixels',rendered.tobytes()==original.tobytes())
        page.locator('.stem-annotated').first.scroll_into_view_if_needed();page.screenshot(path=str(OUT/'real-sample.png'))
    check('no failed browser network requests',network==[])
    check('no browser console errors',console==[])
    check('no browser JavaScript errors',errors==[])
    report['errors']=errors;report['network_errors']=network;report['console_errors']=console;report['zip_members']=archive.namelist()
    browser.close()
(OUT/'browser-report.json').write_text(json.dumps(report,indent=2))
print(json.dumps(report,indent=2))
