title: Anomaly Detection
type: community
group: Anomaly Detection
image:
details: |
  <h1>Segment anomalous regions on images of an object</h1>
  <dl>
    <dt>Industry Applications</dt>
    <dt>Anomaly detection</dt>
  </dl>
config: |
  <View>
    <Labels name="labels" toName="image">
      <Label value="Anomaly" background="rgba(200, 20, 20, 0.7)" />
    </Labels>
    <Image name="image" value="$image" zoom="true" />
    <Brush name="brush" toName="image" />
    <MagicWand name="wand" toName="image" />
    <Rectangle name="rect" toName="image" smart="true" />
  </View>
