RUN git clone --depth 1 https://github.com/blaz-r/SuperSimpleNet .

COPY ${src}/*.patch .
RUN git apply *.patch && rm *.patch

RUN uv venv --python 3.12
RUN uv pip install -r requirements.txt
RUN uv pip install pytorch_lightning lightning opencv-python kornia tifffile psutil mlflow

COPY ${src}/train .
