title: Orientation Detection
type: community
group: Orientation Detection
image:
details: |
  <h1>Annotate object position and orientation</h1>
  <dl>
    <dt>Industry Applications</dt>
    <dt>Material sciences</dt>
  </dl>
config: |
  <View>
    <Labels name="labels" toName="image">
        <Label value="Object" background="rgba(20, 20, 200, 0.7)" />
    </Labels>
    <Image name="image" value="$image" zoom="true" />
    <Vector name="vector" toName="image" smart="true" />
  </View>
